CREATE TABLE "serie" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "map" image
);

CREATE TABLE "photo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "photo" image,
  "latitude" double,
  "longitude" double,
  "serie_id" int
);

ALTER TABLE "photo" ADD FOREIGN KEY ("serie_id") REFERENCES "serie" ("id");
