CREATE TABLE "serie" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titre" varchar,
  "latitude" decimal,
  "longitude" decimal,
  "largeur" int
);

CREATE TABLE "photo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "photo" varchar,
  "latitude" decimal,
  "longitude" decimal,
  "serie_id" int
);

ALTER TABLE "photo" ADD FOREIGN KEY ("serie_id") REFERENCES "serie" ("id");
